import { getSession } from '@/lib/session';
import { redirect } from 'next/navigation';
import sql from '@/lib/db';
import Link from 'next/link';

const BG     = '#07080B';
const CARD   = '#0e1014';
const BORDER = '#1a1d24';
const FONT   = 'var(--font-inter), Inter, sans-serif';

const TYPE_LABELS: Record<string, string> = {
  waste_summary:  'Waste Summary',
  contamination:  'Contamination',
  cost_analysis:  'Cost Analysis',
  diversion_rate: 'Diversion Rate',
  custom:         'Custom',
};

const TYPE_COLORS: Record<string, string> = {
  waste_summary:  '#60a5fa',
  contamination:  '#f87171',
  cost_analysis:  '#34d399',
  diversion_rate: '#a78bfa',
  custom:         '#fbbf24',
};

export default async function ReportsPage() {
  const session = await getSession();
  if (!session) redirect('/login');

  const reports = await sql`
    SELECT
      r.id, r.report_type, r.report_title, r.created_at,
      u.name  AS created_by_name,
      uf.file_name AS source_file_name
    FROM reports r
    JOIN users u ON u.id = r.created_by
    LEFT JOIN uploaded_files uf ON uf.id = r.source_file_id
    WHERE r.organisation_id = ${session.organisationId}
    ORDER BY r.created_at DESC
  `;

  return (
    <div style={{ background: BG, minHeight: 'calc(100vh - 52px)', fontFamily: FONT, color: '#f9fafb', padding: '40px 40px' }}>
      <div style={{ maxWidth: 900, margin: '0 auto' }}>

        <div style={{ marginBottom: 32 }}>
          <h1 style={{ fontSize: 22, fontWeight: 700, letterSpacing: '-0.02em', margin: 0 }}>Reports</h1>
          <p style={{ color: '#6b7280', fontSize: 13, marginTop: 4, marginBottom: 0 }}>
            {reports.length} report{reports.length !== 1 ? 's' : ''} — generated by HLNA
          </p>
        </div>

        {reports.length === 0 ? (
          <div style={{ background: CARD, border: `1px solid ${BORDER}`, borderRadius: 12, padding: '48px 32px', textAlign: 'center' }}>
            <p style={{ color: '#4b5563', fontSize: 14, margin: '0 0 16px' }}>No reports yet.</p>
            <Link href="/data" style={{ color: '#7c3aed', fontSize: 13, textDecoration: 'none' }}>
              Upload data and generate your first report →
            </Link>
          </div>
        ) : (
          <div style={{ background: CARD, border: `1px solid ${BORDER}`, borderRadius: 12, overflow: 'hidden' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <thead>
                <tr style={{ borderBottom: `1px solid ${BORDER}` }}>
                  {['Title', 'Type', 'Source File', 'Created by', 'Date', ''].map(h => (
                    <th key={h} style={thStyle}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {reports.map((r, i) => (
                  <tr key={String(r.id)} style={{ borderBottom: i < reports.length - 1 ? `1px solid ${BORDER}` : 'none' }}>
                    <td style={{ padding: '14px 16px', fontSize: 13, fontWeight: 500, maxWidth: 280, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                      <Link href={`/reports/${r.id}`} style={{ color: '#f9fafb', textDecoration: 'none' }}
                        onMouseEnter={undefined}>
                        {String(r.report_title)}
                      </Link>
                    </td>
                    <td style={{ padding: '14px 16px' }}>
                      <span style={{
                        fontSize: 11, fontWeight: 600,
                        color: TYPE_COLORS[String(r.report_type)] ?? '#9ca3af',
                        background: `${TYPE_COLORS[String(r.report_type)] ?? '#9ca3af'}18`,
                        padding: '3px 8px', borderRadius: 4,
                      }}>
                        {TYPE_LABELS[String(r.report_type)] ?? r.report_type}
                      </span>
                    </td>
                    <td style={{ padding: '14px 16px', fontSize: 12, color: '#6b7280' }}>
                      {r.source_file_name ? String(r.source_file_name) : <span style={{ color: '#4b5563', fontStyle: 'italic' }}>All data</span>}
                    </td>
                    <td style={{ padding: '14px 16px', fontSize: 13, color: '#6b7280' }}>{String(r.created_by_name)}</td>
                    <td style={{ padding: '14px 16px', fontSize: 12, color: '#4b5563' }}>{new Date(String(r.created_at)).toLocaleDateString()}</td>
                    <td style={{ padding: '14px 16px' }}>
                      <Link href={`/reports/${r.id}`} style={{ fontSize: 12, color: '#7c3aed', textDecoration: 'none' }}>View →</Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}

const thStyle: React.CSSProperties = { padding: '12px 16px', textAlign: 'left', color: '#6b7280', fontSize: 11, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.06em', whiteSpace: 'nowrap' };
