import { getSession } from '@/lib/session';
import { redirect } from 'next/navigation';
import sql from '@/lib/db';
import Link from 'next/link';
import { PageHeader, StateMessage, TableContainer, tableStyles } from '@/components/ui/app';
import styles from './Reports.module.css';

const TYPE_LABELS: Record<string, string> = {
  waste_summary:  'Waste Summary',
  contamination:  'Contamination',
  cost_analysis:  'Cost Analysis',
  diversion_rate: 'Diversion Rate',
  custom:         'Custom',
};

// Report-type category hues (data encoding) — rendered on the type dot only.
const TYPE_COLORS: Record<string, string> = {
  waste_summary:  '#60a5fa',
  contamination:  '#f87171',
  cost_analysis:  '#34d399',
  diversion_rate: '#a78bfa',
  custom:         '#fbbf24',
};

export default async function ReportsPage() {
  const session = await getSession();
  if (!session) redirect('/login');

  const reports = await sql`
    SELECT
      r.id, r.report_type, r.report_title, r.created_at,
      u.name  AS created_by_name,
      uf.file_name AS source_file_name
    FROM reports r
    JOIN users u ON u.id = r.created_by
    LEFT JOIN uploaded_files uf ON uf.id = r.source_file_id
    WHERE r.organisation_id = ${session.organisationId}
    ORDER BY r.created_at DESC
  `;

  return (
    <div className={styles.page}>
      <div className={styles.inner}>
        <PageHeader
          title="Reports"
          description={
            <>
              {reports.length} report{reports.length !== 1 ? 's' : ''} — generated by HLNA
            </>
          }
        />

        {reports.length === 0 ? (
          <StateMessage
            kind="empty"
            size="page"
            className={styles.empty}
            title="No reports yet."
            action={
              <Link href="/data" className={styles.emptyLink}>
                Upload data and generate your first report →
              </Link>
            }
          />
        ) : (
          <TableContainer label="Reports" minWidth={720}>
            <table className={tableStyles.table}>
              <thead>
                <tr>
                  {['Title', 'Type', 'Source File', 'Created by', 'Date', ''].map(h => (
                    <th key={h} scope="col" className={h === '' ? tableStyles.actions : undefined}>
                      {h === '' ? <span className={styles.srOnly}>Actions</span> : h}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {reports.map(r => {
                  const typeColor = TYPE_COLORS[String(r.report_type)] ?? '#9ca3af';

                  return (
                    <tr key={String(r.id)}>
                      <td className={`${tableStyles.primary} ${styles.title}`}>
                        <Link href={`/reports/${r.id}`}>
                          {String(r.report_title)}
                        </Link>
                      </td>
                      <td>
                        <span className={styles.type}>
                          <span className={styles.typeDot} style={{ background: typeColor }} aria-hidden="true" />
                          {TYPE_LABELS[String(r.report_type)] ?? r.report_type}
                        </span>
                      </td>
                      <td>
                        {r.source_file_name
                          ? String(r.source_file_name)
                          : (
                            <span className={styles.allData}>
                              All data
                            </span>
                          )}
                      </td>
                      <td>
                        {String(r.created_by_name)}
                      </td>
                      <td>
                        {new Date(String(r.created_at)).toLocaleDateString()}
                      </td>
                      <td className={tableStyles.actions}>
                        <Link href={`/reports/${r.id}`} className={tableStyles.link} aria-label={`View ${String(r.report_title)}`}>
                          View →
                        </Link>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </TableContainer>
        )}
      </div>
    </div>
  );
}
