import { getSession } from '@/lib/session';
import { redirect } from 'next/navigation';
import sql from '@/lib/db';
import Link from 'next/link';
import { Badge, SectionHeader, Surface } from '@/components/ui';

const TYPE_LABELS: Record<string, string> = {
  waste_summary:  'Waste Summary',
  contamination:  'Contamination',
  cost_analysis:  'Cost Analysis',
  diversion_rate: 'Diversion Rate',
  custom:         'Custom',
};

const TYPE_COLORS: Record<string, string> = {
  waste_summary:  '#60a5fa',
  contamination:  '#f87171',
  cost_analysis:  '#34d399',
  diversion_rate: '#a78bfa',
  custom:         '#fbbf24',
};

export default async function ReportsPage() {
  const session = await getSession();
  if (!session) redirect('/login');

  const reports = await sql`
    SELECT
      r.id, r.report_type, r.report_title, r.created_at,
      u.name  AS created_by_name,
      uf.file_name AS source_file_name
    FROM reports r
    JOIN users u ON u.id = r.created_by
    LEFT JOIN uploaded_files uf ON uf.id = r.source_file_id
    WHERE r.organisation_id = ${session.organisationId}
    ORDER BY r.created_at DESC
  `;

  return (
    <div
      style={{
        background: 'var(--bb-canvas)',
        minHeight: 'calc(100vh - 52px)',
        fontFamily: 'var(--bb-font-sans)',
        color: 'var(--bb-text-primary)',
        padding: '40px 40px',
      }}
    >
      <div style={{ maxWidth: 900, margin: '0 auto' }}>
        <SectionHeader
          title="Reports"
          description={
            <>
              {reports.length} report{reports.length !== 1 ? 's' : ''} — generated by HLNA
            </>
          }
          style={{ marginBottom: 'var(--bb-space-9)' }}
        />

        {reports.length === 0 ? (
          <Surface
            variant="base"
            radius="xl"
            style={{
              padding: '48px 32px',
              textAlign: 'center',
            }}
          >
            <p
              style={{
                color: 'var(--bb-text-muted)',
                fontSize: 'var(--bb-type-numeric-size)',
                margin: '0 0 var(--bb-space-6)',
              }}
            >
              No reports yet.
            </p>
            <Link
              href="/data"
              style={{
                color: 'var(--bb-accent-400)',
                fontSize: 'var(--bb-type-body-size)',
                textDecoration: 'none',
              }}
            >
              Upload data and generate your first report →
            </Link>
          </Surface>
        ) : (
          <Surface
            variant="base"
            radius="xl"
            style={{ overflow: 'hidden' }}
          >
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <thead>
                <tr style={{ borderBottom: '1px solid var(--bb-border-default)' }}>
                  {['Title', 'Type', 'Source File', 'Created by', 'Date', ''].map(h => (
                    <th key={h} style={thStyle}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {reports.map((r, i) => {
                  const typeColor = TYPE_COLORS[String(r.report_type)] ?? '#9ca3af';

                  return (
                    <tr
                      key={String(r.id)}
                      style={{
                        borderBottom: i < reports.length - 1
                          ? '1px solid var(--bb-border-subtle)'
                          : 'none',
                      }}
                    >
                      <td
                        style={{
                          padding: '14px 16px',
                          fontSize: 'var(--bb-type-body-size)',
                          fontWeight: 500,
                          maxWidth: 280,
                          overflow: 'hidden',
                          textOverflow: 'ellipsis',
                          whiteSpace: 'nowrap',
                        }}
                      >
                        <Link
                          href={`/reports/${r.id}`}
                          style={{
                            color: 'var(--bb-text-primary)',
                            textDecoration: 'none',
                          }}
                          onMouseEnter={undefined}
                        >
                          {String(r.report_title)}
                        </Link>
                      </td>
                      <td style={{ padding: '14px 16px' }}>
                        <Badge
                          variant="neutral"
                          style={{
                            color: typeColor,
                            background: `${typeColor}18`,
                            borderColor: `${typeColor}30`,
                          }}
                        >
                          {TYPE_LABELS[String(r.report_type)] ?? r.report_type}
                        </Badge>
                      </td>
                      <td
                        style={{
                          padding: '14px 16px',
                          fontSize: 'var(--bb-type-body-sm-size)',
                          color: 'var(--bb-text-tertiary)',
                        }}
                      >
                        {r.source_file_name
                          ? String(r.source_file_name)
                          : (
                            <span style={{ color: 'var(--bb-text-muted)', fontStyle: 'italic' }}>
                              All data
                            </span>
                          )}
                      </td>
                      <td
                        style={{
                          padding: '14px 16px',
                          fontSize: 'var(--bb-type-body-size)',
                          color: 'var(--bb-text-tertiary)',
                        }}
                      >
                        {String(r.created_by_name)}
                      </td>
                      <td
                        style={{
                          padding: '14px 16px',
                          fontSize: 'var(--bb-type-body-sm-size)',
                          color: 'var(--bb-text-muted)',
                        }}
                      >
                        {new Date(String(r.created_at)).toLocaleDateString()}
                      </td>
                      <td style={{ padding: '14px 16px' }}>
                        <Link
                          href={`/reports/${r.id}`}
                          style={{
                            fontSize: 'var(--bb-type-body-sm-size)',
                            color: 'var(--bb-accent-400)',
                            textDecoration: 'none',
                          }}
                        >
                          View →
                        </Link>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </Surface>
        )}
      </div>
    </div>
  );
}

const thStyle: React.CSSProperties = {
  padding: '12px 16px',
  textAlign: 'left',
  color: 'var(--bb-text-muted)',
  fontSize: 'var(--bb-type-label-size)',
  fontWeight: 'var(--bb-type-label-weight)',
  textTransform: 'uppercase',
  letterSpacing: '0.06em',
  whiteSpace: 'nowrap',
};
