-- BrainBase Assurance — initial risk levels for the Brainbase organisation.
-- PREPARED ARTIFACT ONLY. NOT run automatically. Not applied to any
-- environment by the branch that adds it.
--
-- Inserts the four-level scale Brainbase starts with:
--
--   code     name     rank  requires_verification  description
--   LOW      Low       10   false                  Minor risk that can be managed through routine controls.
--   MEDIUM   Medium    20   false                  Moderate risk requiring a planned and monitored response.
--   HIGH     High      30   true                   Significant risk requiring prompt management attention.
--   EXTREME  Extreme   40   true                   Severe risk requiring immediate attention and action.
--
-- for organisation 1732569e-6350-495e-aa6a-7218ce7bf749 (Brainbase) only.
-- Row ids are generated by PostgreSQL (gen_random_uuid()); created_by is
-- NULL (controlled bootstrap, not a user action).
--
-- Semantics (see docs/assurance/admin-guide.md "Risk levels"):
--   * rank is the only severity/order field (higher = more severe). Ranks
--     are spaced by 10 so a level can be inserted later without renumbering
--     (UNIQUE (organisation_id, rank)).
--   * The dashboard treats the two highest-ranked ACTIVE levels as
--     "serious" — with this scale, High and Extreme.
--   * requires_verification records INTENDED future policy only. No
--     application logic reads it today; it does not make High/Extreme
--     actions require verification.
--
-- Safety (fail closed — the whole file is one transaction):
--   Guards: the organisation exists and is named 'Brainbase'; the
--   'assurance' module exists and is active; Brainbase has an ENABLED
--   'assurance' entitlement. Any guard failing -> RAISE EXCEPTION.
--   CASE A  Brainbase has zero risk levels      -> insert exactly the four rows.
--   CASE B  Brainbase has exactly these four rows (same code, name,
--           description, rank, is_active = true, requires_verification)
--                                               -> NO-OP (NOTICE only).
--   CASE C  anything else (partial set, extra rows, different
--           name/description/rank/flags, inactive rows)
--                                               -> RAISE EXCEPTION, nothing changes.
--   It never updates, renames, re-ranks, reactivates or deletes a row, and
--   never touches any other organisation or any other table.
--
-- Deliberately NO audit_logs row: like the capability registration and the
-- /admin/orgs entitlement, this bootstrap's change record is the deployment
-- handoff. Whoever executes it MUST record there:
--   - authorisation (who approved the Production write)
--   - executor (who/what ran it, and how)
--   - timestamp (UTC)
--   - organisation (Brainbase, 1732569e-6350-495e-aa6a-7218ce7bf749)
--   - the git commit containing this exact file
--   - before/after verification (see the queries at the end of this file)
-- First-class configuration auditing belongs with the future
-- Assurance -> Settings -> Risk levels admin screen.
--
-- Correction after use: once any incident/investigation/finding references
-- a level, never delete it (composite FKs). Prefer deactivating it
-- (is_active = false) and adding a replacement, or a separately reviewed,
-- controlled UPDATE of name/description.
--
-- Depends on: A0.1C (scripts/create-assurance-core-a01c.sql) applied, and
-- scripts/seed-assurance-capability.sql + the Brainbase entitlement.
-- Proven by: bash scripts/tests/verify-assurance-risk-bootstrap.sh

BEGIN;

DO $$
DECLARE
  target_org CONSTANT TEXT := '1732569e-6350-495e-aa6a-7218ce7bf749';
  expected   CONSTANT JSONB := '[
    {"code": "LOW",     "name": "Low",     "rank": 10, "requires_verification": false,
     "description": "Minor risk that can be managed through routine controls."},
    {"code": "MEDIUM",  "name": "Medium",  "rank": 20, "requires_verification": false,
     "description": "Moderate risk requiring a planned and monitored response."},
    {"code": "HIGH",    "name": "High",    "rank": 30, "requires_verification": true,
     "description": "Significant risk requiring prompt management attention."},
    {"code": "EXTREME", "name": "Extreme", "rank": 40, "requires_verification": true,
     "description": "Severe risk requiring immediate attention and action."}
  ]'::jsonb;
  org_name        TEXT;
  module_active   BOOLEAN;
  entitlement_on  BOOLEAN;
  existing_count  INTEGER;
  matching_count  INTEGER;
BEGIN
  -- Serialise against any concurrent writer for the duration of this
  -- transaction (readers are not blocked).
  LOCK TABLE assurance_risk_levels IN SHARE ROW EXCLUSIVE MODE;

  SELECT name INTO org_name FROM organisations WHERE id = target_org;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Assurance risk bootstrap refused: organisation % does not exist.', target_org;
  END IF;
  IF org_name IS DISTINCT FROM 'Brainbase' THEN
    RAISE EXCEPTION 'Assurance risk bootstrap refused: organisation % is named %, expected Brainbase.', target_org, org_name;
  END IF;

  SELECT active INTO module_active FROM modules WHERE key = 'assurance';
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Assurance risk bootstrap refused: the assurance module is not registered.';
  END IF;
  IF module_active IS NOT TRUE THEN
    RAISE EXCEPTION 'Assurance risk bootstrap refused: the assurance module is not active.';
  END IF;

  SELECT enabled INTO entitlement_on
    FROM organisation_modules WHERE organisation_id = target_org AND module_key = 'assurance';
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Assurance risk bootstrap refused: Brainbase has no assurance entitlement.';
  END IF;
  IF entitlement_on IS NOT TRUE THEN
    RAISE EXCEPTION 'Assurance risk bootstrap refused: the Brainbase assurance entitlement is disabled.';
  END IF;

  SELECT count(*) INTO existing_count FROM assurance_risk_levels WHERE organisation_id = target_org;

  IF existing_count = 0 THEN
    -- CASE A
    INSERT INTO assurance_risk_levels (organisation_id, code, name, description, rank, is_active, requires_verification)
    SELECT target_org, e.code, e.name, e.description, e.rank, true, e.requires_verification
    FROM jsonb_to_recordset(expected) AS e(code TEXT, name TEXT, description TEXT, rank INTEGER, requires_verification BOOLEAN);
    RAISE NOTICE 'Assurance risk bootstrap: inserted 4 risk levels for Brainbase.';
  END IF;

  -- CASE A post-condition and CASE B check are the same exact-match test.
  SELECT count(*) INTO existing_count FROM assurance_risk_levels WHERE organisation_id = target_org;
  SELECT count(*) INTO matching_count
    FROM assurance_risk_levels r
    JOIN jsonb_to_recordset(expected) AS e(code TEXT, name TEXT, description TEXT, rank INTEGER, requires_verification BOOLEAN)
      ON r.code = e.code
     AND r.name = e.name
     AND r.description IS NOT DISTINCT FROM e.description
     AND r.rank = e.rank
     AND r.is_active = true
     AND r.requires_verification = e.requires_verification
    WHERE r.organisation_id = target_org;

  IF existing_count <> 4 OR matching_count <> 4 THEN
    -- CASE C (the exception rolls back anything this block did)
    RAISE EXCEPTION 'Assurance risk bootstrap refused: Brainbase already has a different risk-level configuration (% rows, % matching the reviewed set). Nothing was changed.',
      existing_count, matching_count;
  END IF;

  RAISE NOTICE 'Assurance risk bootstrap: Brainbase risk levels match the reviewed set (4 rows).';
END
$$;

COMMIT;

-- Before/after verification for the handoff (read-only):
--   SELECT code, name, rank, is_active, requires_verification, description
--   FROM assurance_risk_levels
--   WHERE organisation_id = '1732569e-6350-495e-aa6a-7218ce7bf749'
--   ORDER BY rank DESC;
--   -- expected after: EXTREME 40 t t / HIGH 30 t t / MEDIUM 20 t f / LOW 10 t f
--   SELECT count(*) FROM assurance_risk_levels
--   WHERE organisation_id <> '1732569e-6350-495e-aa6a-7218ce7bf749';  -- unchanged
