// A display boundary, not authorization or a retry policy. Unknown diagnostics
// must never become user-visible references, even when they resemble codes.
const references = new Set([
  "UNAUTHORIZED", "FORBIDDEN", "UPLOAD_NOT_FOUND", "REVIEW_NOT_FOUND",
  "PROFILE_NOT_COMPLETE", "PROFILER_VERSION_UNSUPPORTED", "REVIEW_PROFILE_CHANGED",
  "PROFILE_LINEAGE_MISMATCH", "DATASET_CONTEXT_MISMATCH", "QUALITY_HOLD",
  "REVIEW_INPUT_INVALID", "REVIEW_ACTOR_INVALID", "REVIEW_RECORD_INVALID",
  "REVIEW_READ_FAILED", "REVIEW_SAVE_FAILED", "REVIEW_PLAN_FAILED",
  "CONTEXT_INPUT_INVALID", "CONTEXT_READ_FAILED", "DATASET_CONTEXT_INVALID",
  "PROFILE_EVIDENCE_INVALID", "PROFILE_COUNTS_INVALID", "PROFILE_OPERATION_NOT_SUPPORTED",
  "ANALYSIS_EVALUATION_FAILED", "INVALID_REQUEST", "UNSUPPORTED_CAPABILITY_VERSION",
  "CAPABILITY_NOT_AVAILABLE", "PLAN_KIND_NOT_SUPPORTED", "QUALITY_STATE_INVALID",
  "SCHEMA_QUALITY_LINEAGE_MISMATCH", "PROFILE_SCHEMA_LINEAGE_MISMATCH",
  "CHOICE_REQUIRED", "UNKNOWN_COLUMN", "DUPLICATE_CHOICE", "ROLE_NOT_CANDIDATE",
  "CHOICE_NOT_ALLOWED_FOR_AUTO_RESOLVED_COLUMN", "DECISION_REQUIRED",
  "DUPLICATE_DECISION", "UNKNOWN_REVIEW_ITEM", "INVALID_DECISION_FOR_NOTICE",
  "INVALID_DECISION_FOR_REQUIRED_REVIEW", "COUNT_RESPONSE_INVALID",
  "COUNT_RESPONSE_MISMATCH", "RESPONSE_INVALID", "REQUEST_FAILED",
]);

export function analysisFailureReference(value: unknown): string {
  return typeof value === "string" && references.has(value) ? value : "REQUEST_FAILED";
}
